AllCops:
  DisplayCopNames: true

Style/Documentation:
  Enabled: false
Style/RaiseArgs:
  Enabled: false
Style/ClassVars:
  Enabled: false
Metrics/LineLength:
  Max: 100
Metrics/BlockLength:
  Max: 200
